name: Python CI

on:
  push:
    branches:
      - main  # Trigger workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull request to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # The job runs on the latest version of Ubuntu

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Set the Python version you want (e.g., 3.9)

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip to the latest version
        pip install -r requirements.txt  # Install dependencies from the requirements.txt

    # Run tests
    - name: Run tests
      run: |
        pytest  # Run tests using pytest
