name: Python CI

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu for running the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository to get access to the code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Set the Python version you want to use (e.g., 3.9)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from the requirements.txt

    - name: Run tests
      run: |
        pytest  # Run tests using pytest. You can change this if using another test framework
